"use strict";

const PYODIDE_DIR = new URL("pyodide/", location.href).href;
importScripts(PYODIDE_DIR + "pyodide.js");

const WHEEL_URL = "wheels/holoso-0.1.0-py3-none-any.whl";

let py = null;

const status = (msg) => postMessage({ type: "status", msg });

// Demo kernels are static source files shipped with the site (demos/), not part of the holoso wheel; the picker
// is built here so it never depends on the engine being up or on a synth-side demo package.
async function loadDemos() {
  const manifest = await (await fetch("demos/manifest.json")).json();
  // `extras` are sibling .py files (e.g. iir1_hpf needs iir1_lpf): each is fetched once and shipped with the demo;
  // the worker forwards them to the driver, which writes each into /user/<filename> before importing the main module.
  return Promise.all(
    manifest.map(async (d) => {
      const source = await (await fetch("demos/" + d.file)).text();
      const extraFiles = await Promise.all(
        (d.extras || []).map(async (name) => [name, await (await fetch("demos/" + name)).text()])
      );
      const extras = Object.fromEntries(extraFiles);
      return { id: d.id, label: d.label, filename: d.file, source, extras };
    })
  );
}

async function init() {
  status("loading Pyodide runtime…");
  py = await loadPyodide({ indexURL: PYODIDE_DIR });
  status("loading numpy + scipy + sympy…");
  await py.loadPackage(["micropip", "numpy", "scipy", "sympy"]);

  status("installing holoso + extras…");
  // cache: "reload" forces a network fetch, bypassing any stale HTTP-cache entry. The wheel keeps a fixed
  // filename across deploys, so a browser that once cached it as immutable would otherwise pin an old build.
  // wheels/extra-manifest.json is generated by `make vendor-jaxtyping`: an ordered list of pure-Python wheels
  // (deps first) that upstream examples need but pyodide-lock does not ship. The worker installs each from
  // emfs:/ so nothing reaches PyPI at runtime.
  const wheelFiles = [WHEEL_URL.split("/").pop()];
  const bytes = new Uint8Array(await (await fetch(WHEEL_URL, { cache: "reload" })).arrayBuffer());
  py.FS.writeFile("/" + wheelFiles[0], bytes);
  const extras = await (await fetch("wheels/extra-manifest.json", { cache: "reload" })).json();
  for (const name of extras) {
    const buf = new Uint8Array(await (await fetch("wheels/" + name, { cache: "reload" })).arrayBuffer());
    py.FS.writeFile("/" + name, buf);
    wheelFiles.push(name);
  }
  const installs = wheelFiles.map((n) => `await micropip.install("emfs:/${n}", deps=False)`).join("\n");
  await py.runPythonAsync(`import micropip\n${installs}\n`);

  py.runPython(await (await fetch("driver.py")).text());
  const versions = py.runPython(
    "import holoso, sys, numpy, scipy, sympy, jaxtyping; " +
      "f'holoso {holoso.__version__} · CPython {sys.version.split()[0]} · numpy {numpy.__version__} · scipy {scipy.__version__} · sympy {sympy.__version__} · jaxtyping {jaxtyping.__version__}'"
  );
  const examples = await loadDemos();
  postMessage({ type: "ready", versions, examples });
}

function run(req) {
  py.globals.set("_filename", req.filename || "main.py");
  py.globals.set("_src", req.source);
  py.globals.set("_extras", req.extras ? JSON.stringify(req.extras) : "");
  // Live streaming: the driver's _StreamRedirect picks this JS callback up from globals and fires it per
  // newline. postMessage is non-blocking here even though Python runs synchronously on this worker --
  // the main thread drains its queue on its own, so log lines paint as the run progresses.
  py.globals.set("_stream_line", (stream, line) => {
    try { postMessage({ type: "stream", id: req.id, stream: String(stream), line: String(line) }); } catch {}
  });
  const json = py.runPython("run_script(_filename, _src, _extras)");
  postMessage({ type: "result", id: req.id, json });
}

onmessage = async (e) => {
  const m = e.data;
  try {
    if (m.type === "init") await init();
    else if (m.type === "run") run(m);
  } catch (err) {
    const message = String((err && err.message) || err);
    if (m.type === "init") postMessage({ type: "fatal", msg: message });
    else postMessage({ type: "result", id: m.id, json: JSON.stringify({ ok: false, error: { kind: "WorkerError", message }, stdout: "", stderr: "", files: [] }) });
  }
};
