import { loadPyodide } from "pyodide";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const WEB = fileURLToPath(new URL("../", import.meta.url));
const SYNTH = process.env.SYNTH || WEB + "../holoso-synth";
const WHEEL = `${SYNTH.replace(/\/$/, "")}/dist/holoso-0.1.0-py3-none-any.whl`;
const DRIVER = WEB + "driver.py";
const DEMOS = WEB + "demos";
const EXTRA_WHEELS = WEB + "wheels";  // generated by `make vendor-jaxtyping`

// Mirror the worker: the demo corpus is static source files listed by demos/manifest.json -- not the wheel.
// Each manifest entry may also list sibling .py files via `extras`; they are read alongside and passed
// to the driver as a {filename: content} bundle so cross-file imports (ekf1_stateful imports ekf1_stateless)
// resolve when the runner exec's the script as __main__.
function loadDemos() {
  return JSON.parse(readFileSync(`${DEMOS}/manifest.json`, "utf8")).map((d) => {
    const extras = Object.fromEntries((d.extras || []).map((n) => [n, readFileSync(`${DEMOS}/${n}`, "utf8")]));
    return {
      id: d.id,
      label: d.label,
      filename: d.file,
      source: readFileSync(`${DEMOS}/${d.file}`, "utf8"),
      extras,
    };
  });
}

// Demos that ship a runnable main() -- the script must succeed, emit at least one .v + one .html, and
// print something to stdout. The rest define a kernel for downstream import but have no main(), so a
// successful run is one that exits cleanly with an empty file list.
const HAS_MAIN = new Set(["ekf1_stateful", "ekf1_stateless", "madd", "poly3", "trapezoidal_leaky_streaming_integrator"]);

const log = (...a) => process.stdout.write(a.join(" ") + "\n");
let failures = 0;
function check(cond, msg) {
  log(`${cond ? "  ok  " : " FAIL "} ${msg}`);
  if (!cond) failures++;
}

function run(py, filename, src, extras = {}) {
  py.globals.set("_filename", filename);
  py.globals.set("_src", src);
  py.globals.set("_extras", JSON.stringify(extras));
  return JSON.parse(py.runPython("run_script(_filename, _src, _extras)"));
}

try {
  const py = await loadPyodide();
  await py.loadPackage(["micropip", "numpy", "scipy", "sympy"]);
  const wheels = ["holoso-0.1.0-py3-none-any.whl"];
  py.FS.writeFile("/" + wheels[0], readFileSync(WHEEL));
  for (const name of JSON.parse(readFileSync(`${EXTRA_WHEELS}/extra-manifest.json`, "utf8"))) {
    py.FS.writeFile("/" + name, readFileSync(`${EXTRA_WHEELS}/${name}`));
    wheels.push(name);
  }
  const installs = wheels.map((n) => `await micropip.install("emfs:/${n}", deps=False)`).join("\n");
  await py.runPythonAsync(`import micropip\n${installs}\n`);
  py.runPython(readFileSync(DRIVER, "utf8"));

  log("\n=== demo kernels load + run ===");
  const demos = loadDemos();
  check(demos.length >= 5, `loaded ${demos.length} demo kernels`);
  for (const d of demos) {
    check(typeof d.id === "string" && typeof d.filename === "string" && d.source.length > 0, `demo ${d.id}: shape`);
    const r = run(py, d.filename, d.source, d.extras);
    if (!r.ok) {
      const msg = (r.error?.message || "").split("\n").slice(-5).join(" | ");
      check(false, `demo ${d.id}: script ran (${r.error?.kind}: ${msg})`);
      continue;
    }
    check(true, `demo ${d.id}: script ran cleanly`);
    if (HAS_MAIN.has(d.id)) {
      const exts = r.files.map((f) => f.ext);
      check(exts.includes("v"), `demo ${d.id}: emits at least one .v (${exts.join(",") || "none"})`);
      check(exts.includes("html"), `demo ${d.id}: emits at least one .html (${exts.join(",") || "none"})`);
      check((r.stdout || "").length > 0, `demo ${d.id}: main() printed something (${(r.stdout || "").length} bytes)`);
      // The build dir convention `Path(__file__).parent / "build" / stem` is the contract that lets the UI's
      // tab grouping and resource-estimate path-derivation work; pin it.
      const stem = d.filename.replace(/\.py$/, "");
      check(
        r.files.every((f) => f.path.startsWith(`build/${stem}/`)),
        `demo ${d.id}: artifacts live under build/${stem}/ (got ${r.files.map((f) => f.path).join(", ")})`
      );
    } else {
      check(r.files.length === 0, `demo ${d.id}: defines kernel only, no main() -> no files (got ${r.files.length})`);
    }
  }

  log("\n=== error surfacing ===");
  const importErr = "raise ValueError('boom at import')\n";
  let r = run(py, "boom.py", importErr);
  check(r.ok === false, `import-time raise -> ok=false (kind=${r.error?.kind})`);
  check(r.error?.location?.lineno === 1, `error annotates line 1 (got ${JSON.stringify(r.error?.location)})`);
  check((r.error?.kind || "").includes("ValueError"), `error kind names ValueError (got ${r.error?.kind})`);

  const synthErr =
    "import holoso\n" +
    "def k(a, b):\n" +
    "    if a > b: return a\n" +
    "    return b\n" +
    "def main():\n" +
    "    fmt = holoso.FloatFormat(wexp=8, wman=24)\n" +
    "    ops = holoso.OpConfig(\n" +
    "        holoso.FAddOperator(fmt), holoso.FMulOperator(fmt),\n" +
    "        holoso.FDivOperator(fmt), holoso.FMulILog2OperatorFamily(fmt),\n" +
    "    )\n" +
    "    holoso.synthesize(k, ops=ops)\n" +
    "main()\n";
  r = run(py, "synth_err.py", synthErr);
  check(r.ok === false, `unsupported 'if' rejected mid-main() (kind=${r.error?.kind})`);
  // Holoso's frontend tags this UnsupportedConstruct; if upstream renames the class we want a loud miss.
  check(
    (r.error?.kind || "").toLowerCase().includes("unsupported") || (r.error?.kind || "") === "UnsupportedConstruct",
    `unsupported construct surfaces a Holoso-flavored error kind (got ${r.error?.kind})`
  );

  log("\n=== stdout / stderr capture ===");
  const ioSrc =
    "import sys\n" +
    "print('hello stdout')\n" +
    "print('hello stderr', file=sys.stderr)\n";
  r = run(py, "io.py", ioSrc);
  check(r.ok === true, `plain print() succeeds (kind=${r.error?.kind})`);
  check(r.stdout.includes("hello stdout"), `stdout captured (${JSON.stringify(r.stdout)})`);
  check(r.stderr.includes("hello stderr"), `stderr captured (${JSON.stringify(r.stderr)})`);
  check(r.files.length === 0, `no side-effect files (got ${r.files.length})`);

  log("\n=== file-emit walk ===");
  const writeSrc =
    "from pathlib import Path\n" +
    "out = Path('build/demo')\n" +
    "out.mkdir(parents=True, exist_ok=True)\n" +
    "(out / 'a.v').write_text('module a; endmodule\\n')\n" +
    "(out / 'a.html').write_text('<h1>a</h1>')\n";
  r = run(py, "writer.py", writeSrc);
  check(r.ok === true, `writer script ok (kind=${r.error?.kind})`);
  const paths = r.files.map((f) => f.path).sort();
  check(paths.length === 2, `two files emitted (got ${paths.length}: ${paths.join(", ")})`);
  check(paths.includes("build/demo/a.v"), `build/demo/a.v in list`);
  check(paths.includes("build/demo/a.html"), `build/demo/a.html in list`);
  const vFile = r.files.find((f) => f.ext === "v");
  check(vFile?.content?.includes("module a"), `.v content round-trips`);

  log("\n=== re-run picks up edited siblings ===");
  // The runner clears /user/* from sys.modules + linecache between runs; verify an extras edit is observed.
  const main1 = "from sib import VALUE\nprint(VALUE)\n";
  const sib1 = "VALUE = 1\n";
  const sib2 = "VALUE = 2\n";
  r = run(py, "main.py", main1, { "sib.py": sib1 });
  check(r.ok && r.stdout.trim() === "1", `first run uses sib v1 (stdout=${JSON.stringify(r.stdout)})`);
  r = run(py, "main.py", main1, { "sib.py": sib2 });
  check(r.ok && r.stdout.trim() === "2", `second run sees edited sib v2 (stdout=${JSON.stringify(r.stdout)})`);

  log("\n=== bad request shape ===");
  r = run(py, "x", "print('hi')\n");
  check(r.ok === false && r.error?.kind === "BadRequest", `filename without .py rejected (kind=${r.error?.kind})`);
  r = run(py, "../etc/main.py", "print('hi')\n");
  check(r.ok === false && r.error?.kind === "BadRequest", `path-traversal in filename rejected (kind=${r.error?.kind})`);
  r = run(py, "main.py", "print('hi')\n", { "../x.py": "X = 1\n" });
  check(r.ok === false && r.error?.kind === "BadRequest", `path-traversal in extras rejected (kind=${r.error?.kind})`);

  log(`\n=== ${failures ? failures + " FAILURE(S)" : "ALL CHECKS PASSED"} ===`);
  process.exit(failures ? 1 : 0);
} catch (e) {
  log("FATAL:", (e.message || String(e)).split("\n").slice(0, 25).join("\n"));
  process.exit(1);
}
